### ISSUE TITLE
Поддержка устаревшего наименования xml алгоритма 34.10-2001

### ISSUE THREAD

**Issue by f1lareon6** [CryptoPro/corefx#35]
Добрый день. Могли бы вы добавить для поддержки совместимости старые наименования алгоритмов:
<SignatureMethod Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#gostr34102001-gostr3411\"></SignatureMethod>"
<DigestMethod Algorithm=\"http://www.w3.org/2001/04/xmldsig-more#gostr3411\"></DigestMethod>" ?

Ранее использовал GostCryptography, но в связи с необходимостью переходить на .net core, больше нет такой возможности. Похожая проблема возникала и в том проекте https://github.com/AlexMAS/GostCryptography/issues/11

**Comment by Fasjeit** [comment]
Добрый день. 

Можно пробовать тестовые сборки.
[Windows](https://ci.appveyor.com/project/CryptoPro/corefx/builds/36151101/job/unnsrsqbyfmqr6v4/artifacts)
[Linux](https://ci.appveyor.com/project/CryptoPro/corefx/builds/36151101/job/7eu6nvm72bnm7ps1/artifacts)

**Comment by f1lareon6** [comment]
Работает. Спасибо за столь быстрый ответ.
