### ISSUE TITLE
не ищется сертификат по SubjectName

### ISSUE THREAD

**Issue by mshamito** [CryptoPro/corefx#40]
открываем хранилище на debian 10,  csp 5.0.11998
`X509Store store = new X509Store(StoreName.My, StoreLocation.CurrentUser);
store.Open(OpenFlags.ReadOnly);`
при поиске по DN возвращается пустая коллекция
`store.Certificates.Find(X509FindType.FindBySubjectName, "test2012", true);`
если искать по отпечатку то сертификат находится.
`store.Certificates.Find(X509FindType.FindByThumbprint, "86d6949e285376565406e1e84995e4967959bec2", true);`
в certmgr -list
Subject             : CN=test2012  
SHA1 Hash           : 86d6949e285376565406e1e84995e4967959bec2

**Comment by tolyanich** [comment]
После [коммита](https://github.com/CryptoPro/corefx/commit/3341718ed4b6a7bb993f33f0a4fb59f5cd873c28) должно заработать. Сборку можно взять по [ссылке](https://ci.appveyor.com/project/CryptoPro/corefx/builds/37241418)

**Comment by mshamito** [comment]
спасибо. все заработало.
