### ISSUE TITLE
Ошибка при получении закрытого ключа из сертификата (csp 5.0.11998 KC1)

### ISSUE THREAD

**Issue by Fasjeit** [CryptoPro/corefx#46]
За csp 5.0.11998 KC1 замечено изменение по работе с CNG. В частности метод

```csharp
Interop.crypt32.CryptAcquireCertificatePrivateKey(
                    certificateContext,
                    CryptAcquireFlags.CRYPT_ACQUIRE_ONLY_NCRYPT_KEY_FLAG,
                    IntPtr.Zero,
                    out privateKey,
                    out keySpec,
                    out freeKey
```

возвращает не "key not found", как раньше, а корректный хэндл ключа, что ломает текущую логику, в которой пытается создаться CNG ключ для ГОСТа, и падаем в стабный метод заглушку.

Поведение за версиями 5.0.11736 и 5.0.12099 замечено не было.

Надо поменять логику GetPrivateKey, добавив возможность передавать пустой createCng, что и делать для ГОСТов.

**Comment by Fasjeit** [comment]
сообщение на форуме - https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=123479#post123479

**Comment by maxdm** [comment]
Мы в последних версиях CSP модули CNG интенсивно улучшали. В целом уже многое работает без патчей и драйвера CProCtrl. 
Так что в этом режиме тоже стоит .NET тестировать.
