### ISSUE TITLE
Кириллица в CN при создании сертификатов

### ISSUE THREAD

**Issue by Fasjeit** [CryptoPro/corefx#49]
В настоящий момент при варке сертификата через CertificateRequest в самом сертификате кириллица отображается неверно. Смотреть в сторону функции `CertStrToName`. Пробовал сделать её интероп на unicode, и с ручным переводом в массив байт unicode строки с `byte[]` интеропом. Пока не вышло.
Воспроизводится на Unix.

Тема на форуме:
https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=125604#post125604

**Comment by Danilovonline** [comment]
Добрый день.
Есть прогноз когда будет исправлен баг?

**Comment by Fasjeit** [comment]
Добрый день.
На сл. неделе постараемся посмотреть.

**Comment by Fasjeit** [comment]
Основная проблема - использование функции `CertStrToNameA`. На Windows работало корректно, передавало данные в `1251`. На Unix передавала данные в `UTF8`, от чего было кривое отображения.

Также была замечена ошибка на Windows, при отсутствии русской локали (видимо не использовалась `1251` по умолчанию).

Решили перейти на `CertStrToNameW` + `KeySet.Unicode`. На Windows всё завелось на английском, и ничего не поломалось на русском. Через стандартный маршалинг передаём строку.

На Unix чуть сложнее:

`CertStrToNameW` принимает имя в формате `LPWSTR`. Из [jira](https://jira.cp.ru/browse/CA-3788):
```
Маршаллинг string в функции, принимающие LPWSTR. 
На windows WCHAR это 2 байта (UTF16), на линуксе - 4 (UTF32).
```

Поэтому делаем перевод руками перевод строки в UTF16 и передаём её как `IntPrt` в `CertStrToNameW`. 

Всё заработало.

Ветвимся по таргетам как и раньше по разным файлам с partial классами ([Cryptography/Pal.Windows/X509Pal.X500DistinguishedName.Unix.cs](https://github.com/CryptoPro/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/X509Pal.X500DistinguishedName.Unix.cs) и [X509Pal.X500DistinguishedName.Windows.cs](https://github.com/CryptoPro/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/X509Pal.X500DistinguishedName.Win.cs)), куда вынесли код функции `X500DistinguishedNameEncode` из [X509Pal.X500DistinguishedName.cs](https://github.com/CryptoPro/corefx/blob/master/src/System.Security.Cryptography.X509Certificates/src/Internal/Cryptography/Pal.Windows/X509Pal.X500DistinguishedName.cs).

Добавил пару тестов для Ascii и Unicode CN для гостовых сертификатов. Изменения в мастер ветке.

**Comment by Fasjeit** [comment]
@Danilovonline 
Можно смотреть изменения в последней сборке.
[win](https://ci.appveyor.com/project/CryptoPro/corefx/build/job/ir14dsbsjxscnj7b/artifacts)
[linux](https://ci.appveyor.com/project/CryptoPro/corefx/build/job/5jgntu7i8cwwsqd0/artifacts)
