### ISSUE TITLE
Зачем патчить рантайм?

### ISSUE THREAD

**Issue by govorovvs** [CryptoPro/corefx#51]
Уважаемые разработчики, где можно почитать причины, для чего патчится рантайм .net?

**Comment by Fasjeit** [comment]
Основаная задача проекта - поддержка ГОСТовой криптографии в dotnet core, на том же уровне, на котором поддерживаются зарубежные алгоритмы.

Реализация самих алгоритмов может быть выполнена отдельной бибдиотекой, без внедрения изменений в runtime. Однако проблемы возникают, когда мы хотим пойти дальше и использоваться ГОСТовые алгоритмы для работы с сертификатами, XML и CMS подписями, TLS, и аутентификацией в вебе. Microsoft не предоставляет интерфейсов расширения в данных сценариях для использования алгоритмов отличных от AES\RSA\DSA. Часто в коде встречаются конструкции вида (X509Certificate):

[`https://github.com/dotnet/corefx/blob/5aff0aae8b5abb2440095af9acf9ee59dc2373f4/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs#L196-L230`](https://github.com/dotnet/corefx/blob/5aff0aae8b5abb2440095af9acf9ee59dc2373f4/src/System.Security.Cryptography.X509Certificates/src/System/Security/Cryptography/X509Certificates/X509Certificate2.cs#L196-L230)

Отсюда, если есть потребность использования ГОСТового сертификта нужно либо переписать весь стек методов работы с ними в отдельной библиотеке, либо внести изменения в существующий код. 

Первый способ не позволяет использовать полученные классы внутри существующего кода рантайма. Например, не получится заставить дотнет использовать новый класс сертификатов для работы с XML подписями, придётся переписывать и весь стек работы с SignedXml. Аналогочино для веба. 

Используя второй способ мы дописываем сущуствующий код рантайма для поддержки ГОСТов, внося точечные изменения. В результате мы можем работать с ГОСТовыми сертификатами так же, как с RSA сертификатами в изначальном рантайме, и использовать их аналогично во всех необходимых сценариях.

Отдельно стоит заметить, что в рамках данного проекта под "рантаймом" подразумевается набор стандартных библитек, поставляемых вместе с dotnet (влючая всю криптографию). Изменения вносятся только в проекты, имеющие отношения к криптографии. Вопросами компиляции и исполнения кода в рамках dotnet 3.1 занимается отдельный проект [coreclr](https://github.com/dotnet/coreclr/tree/release/3.1), независящий от corefx.
