### ISSUE TITLE
Неправильно работает AsnEncodedData.Format на Linux

### ISSUE THREAD

**Issue by ekx77** [CryptoPro/corefx#57]
Эта проблема .NET CORE не относится к ГОСТ криптографии, но посмотрите пожалуйста - вдруг удастся легко исправить.

Метод AsnEncodedData.Format на linux работает неправильно.
Он возвращает не полный текст описания расширения, а только первую строку из него.
Видимо, где-то косяк с p/invoke, там через вызов метода из openssl все делается.
При этом сам openssl из командной строки показывает все правильно.
Пример вызова : Programs.cs.txt
[Programs.cs.txt](https://github.com/CryptoPro/corefx/files/8777374/Programs.cs.txt)

Расширения 1.3.6.1.5.5.7.1.1,  2.5.29.32 и 2.5.29.31 нормально выводятся на windows (win.txt), 
на linux через `openssl x509 -inform der -in cert.cer -noout -text ` (openssl.txt)
и обрезаются на linux при выводе через .net core (linux.txt).
[win.txt](https://github.com/CryptoPro/corefx/files/8777378/win.txt)
[linux.txt](https://github.com/CryptoPro/corefx/files/8777383/linux.txt)
[openssl.txt](https://github.com/CryptoPro/corefx/files/8777384/openssl.txt)

**Comment by Fasjeit** [comment]
## Суть проблемы

После получения данных о расширении в виде массива байт, на Linux вызывается `OpenSslAsnFormatter`, который читает asn1 структуру и выводит данные. Сама структура в виде массива байт читает правильно и совпадает с виндовой. Различия только в её дикодировании.

Сущестующая проблема - его вывод отличается от виндового `OpenSslAsnFormatter`. Мы эту сборку не правили, проблема была изначально. MS в курсе, но делать что то не торопятся:

Связанная проблема https://github.com/dotnet/runtime/issues/15445

По вызовам p/invoke особых проблем не наблюдается, он вызывает нативную обёртку для работы через OpenSSL. 

```c
int32_t CryptoNative_X509V3ExtPrint(BIO* out, X509_EXTENSION* ext)
{
    ERR_clear_error();
    return X509V3_EXT_print(out, ext, X509V3_EXT_DEFAULT, /*indent*/ 0);
}
```

Ошибка видимо где то в нативной обёртке. Как правильно работать тут с openSSL понятия не имею. Примера правильной работы нет, а ковыряться там под никсами можно долго.

Перевести всё на crypt32 страшно, не факт что мы поддерживаем нужные функции, да и декодировать asn1 через наш провайдер для RSA сертификатов не очень хочется, даже если заработает, чтоб не создавать ещё одну точку несовместимости.

## Workaround 

Сами ms говорят использовать `AsnReader` и декодировать ручками. 

https://github.com/CryptoPro/corefx/tree/master/src/Common/src/System/Security/Cryptography/Asn1Reader

В core 3.0 он internal, так что надо будет его выкусывать в свой код для использования. 

Есть **отдельный пакет** с ним, который работает в 3.0: `"System.Formats.Asn1" Version="6.0.0"`. Красиво данные не форматирует, но можно допилить. 

Пример как можно организовать работу с ним:
```csharp
internal static class X509ExtensionExtension
{
    public static string SafeFormat(this X509Extension ext)
    {
        switch (ext.Oid.Value)
        {
            case ("1.3.6.1.5.5.7.1.1"):
            {
                var stringBuilder = new StringBuilder();

                var reader = new AsnReader(ext.RawData, AsnEncodingRules.DER);
                var seq = reader.ReadSequence();

                while (seq.HasData)
                {
                    var seq2 = seq.ReadSequence();
                    var objectIdentifier = seq2.ReadObjectIdentifier();
                    stringBuilder.AppendLine(objectIdentifier);

                    Asn1Tag ContextSpecificTag = new Asn1Tag(TagClass.ContextSpecific, 6);
                    var value = seq2.ReadOctetString(ContextSpecificTag);
                    var decodedValue = Encoding.UTF8.GetString(value);
                    stringBuilder.AppendLine(decodedValue);
                }
                return stringBuilder.ToString();
            }
            default:
            {
                return ext.Format(multiLine: true);
            }
        }
    }
}
```

Пример вывода для `1.3.6.1.5.5.7.1.1` (да, friendly описаний нет, добавлять придётся самим, если нужны).
```
1.3.6.1.5.5.7.48.2
http://reporting/aia/8d9be59b14790e2578f2cad8db7d80fe48b0b017.crt
1.3.6.1.5.5.7.48.2
http://ecp.cryptopro.ru/aia/8d9be59b14790e2578f2cad8db7d80fe48b0b017.crt
```

**Comment by ekx77** [comment]
Спасибо! Да, capilte я уже смотрел - там CryptFormatObject как на винде нереализована.
