### ISSUE TITLE
Избавиться от createdump в self-contained сборках на Linux

### ISSUE THREAD

**Issue by ekx77** [CryptoPro/corefx#58]
При dotnet publish в выходные файлы попадает утилита createdump. Это не устраивает регулятора, т.к. в в дистрибутиве не должно быть никаких средств отладки.   
Простое удаление приводит в ошибке. Аналогичная проблема есть и в исходном .NET Core (https://github.com/dotnet/runtime/issues/43716).
От этой утилиты необходимо избавиться.

**Comment by Fasjeit** [comment]
Как писали в этой же ветке - помогает удаление файла `createdump` + модификация `deps.json`.

Нужно удалить узел в зависимостях:
```json
"createdump": {
    "fileVersion": "0.0.0.0"
},
```

Пример, как это можно сделать после publish для проекта с именем `test`:

```sh
cd publish
# удаляем createdump
rm ./createdump
# удаляем узел с createdump, пишем результат в tmp файл
jq "del(..|.\"createdump\"?)" test.deps.json > new.test.deps.json
# удаляем старый файл
rm ./test.deps.json
# заменяем его новым
mv new.test.deps.json test.deps.json
```

После этого проект должен запускаться без ошибок.

**Comment by ekx77** [comment]
Это работает, спасибо!
