### ISSUE TITLE
net7 и обновление версионности

### ISSUE THREAD

**Issue by ParadiseFallen** [CryptoPro/corefx#64]
Привет!. хотелось бы увидеть то, как можно обновить версию .net. 
Какую либо инструкцию. Т.к. проект написан на более свежей версии .net нет возможности опустить эту версию

**Comment by Fasjeit** [comment]
Текущий проект является форком рантайма 3.1 и жестко завязан под его версии и версии sdk.
Завести на каких то других версиях - не получится.

Для 6.0 есть LibCore, который уже можно пробовать для ряда сценариев - https://github.com/CryptoPro/libcore
7.0 нигде не поддерживаем и не будем, перейдём сразу на LTS версию 8.0, когда она появится и когда научимся её поддерживать.

**Comment by ParadiseFallen** [comment]
@Fasjeit спасибо за быстрый ответ!. 

Есть примеры использования libcore для xades-bes + ГИС ЖКХ?

Я так понимаю библиотека не opensource?

**Comment by Fasjeit** [comment]
Библиотека не опенсорс, базовые криптографические примеры есть в Readme, xades из коробки нет.
